version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.2-apache
    volumes:
    - ~/.composer-docker/cache:/root/.composer/cache:delegated
    - ./:/app:delegated
    ports:
    - '8000:80'
    links:
    - mysql-db

  mysql-db:
    image: mysql:5.7
    ports:
    - 3306:3306
    environment:
      MYSQL_DATABASE: yii2basic
      MYSQL_USER: foo
      MYSQL_PASSWORD: bar
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
    - mysql-db
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
    ports:
    - '8080:80'